name: Update README on Docker Hub
env:
  DOCKER_REGISTRY: 91dave
  DOCKER_IMAGE: nginx-basic-proxy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'README.md'

jobs:
  deploy:
    name: Update README on Docker Hub
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2
      
      # Login to Docker Hub
      - name: Login to docker.io registry
        run: |
          echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      # Update Description from Readme
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ env.DOCKER_REGISTRY}}/${{ env.DOCKER_IMAGE }}